### ISSUE TITLE
ImportError: attempted relative import beyond top-level package

### ISSUE THREAD

**Issue by MorganRO8** [PhosphorylatedRabbits/paperscraper#23]
Probably my fault, but I pasted this code:

from paperscraper.get_dumps import biorxiv, medrxiv, chemrxiv
medrxiv()  #  Takes ~30min and should result in ~35 MB file
biorxiv()  # Takes ~1h and should result in ~350 MB file
chemrxiv()  #  Takes ~45min and should result in ~20 MB file

into a get_dumps.py in paperscraper/paperscraper and tried running it using python3 paperscraper, and I got this error:

Traceback (most recent call last):
  File "/home/morgan/anaconda3/envs/scraper/paperscraper/paperscraper/get_dumps.py", line 1, in <module>
    from paperscraper.get_dumps import biorxiv, medrxiv, chemrxiv
  File "/home/morgan/.local/lib/python3.10/site-packages/paperscraper/__init__.py", line 10, in <module>
    from .load_dumps import QUERY_FN_DICT
  File "/home/morgan/.local/lib/python3.10/site-packages/paperscraper/load_dumps.py", line 8, in <module>
    from .arxiv import get_and_dump_arxiv_papers
  File "/home/morgan/.local/lib/python3.10/site-packages/paperscraper/arxiv/__init__.py", line 1, in <module>
    from .arxiv import *  # noqa
  File "/home/morgan/.local/lib/python3.10/site-packages/paperscraper/arxiv/arxiv.py", line 5, in <module>
    import arxiv
  File "/home/morgan/anaconda3/envs/scraper/paperscraper/paperscraper/arxiv/__init__.py", line 1, in <module>
    from .arxiv import *  # noqa
  File "/home/morgan/anaconda3/envs/scraper/paperscraper/paperscraper/arxiv/arxiv.py", line 7, in <module>
    from ..utils import dump_papers
ImportError: attempted relative import beyond top-level package

I'm likely doing something wrong, and I was hoping you could help me figure out what it is in particular. 

Thanks!

-Morgan

Edit: I am using a conda environment to run this, if that makes a difference.

**Comment by jannisborn** [comment]
Hi @MorganRO8,

Thanks for your interest in `paperscraper`. Your mistake was **where** to put `get_dumps.py`. Dont put it **inside** `paperscraper`, just put it somewhere else, e.g., in `/home/morgan/anaconda3/envs/scraper/`.

Feel free to reopen if you need more help
