### ISSUE TITLE
HTTPError for paperscraper.get_dumps.chemrxiv()

### ISSUE THREAD

**Issue by LioHong** [PhosphorylatedRabbits/paperscraper#28]
Hi, I was trying this library out and it worked for `biorxiv()` and `medxriv()`. However, for `chemrxiv()` I kept getting this error:
```
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    xxv_dumps(3)
  File "C:\Users\User\Documents\98_Notes\Data Analytics\use_paperscraper.py", line 37, in xxv_dumps
    chemrxiv()  #  Takes ~45min and should result in ~20 MB file
  File "C:\Users\User\Desktop\Programs\Winpython64_3.11\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\paperscraper\get_dumps\chemrxiv.py", line 42, in chemrxiv
    download_full(save_folder, api)
  File "C:\Users\User\Desktop\Programs\Winpython64_3.11\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\paperscraper\get_dumps\utils\chemrxiv\utils.py", line 132, in download_full
    for preprint in tqdm(api.all_preprints()):
  File "C:\Users\User\Desktop\Programs\Winpython64_3.11\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\tqdm\std.py", line 1178, in __iter__
    for obj in iterable:
  File "C:\Users\User\Desktop\Programs\Winpython64_3.11\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\paperscraper\get_dumps\utils\chemrxiv\chemrxiv_api.py", line 103, in query_generator
    r.raise_for_status()
  File "C:\Users\User\Desktop\Programs\Winpython64_3.11\WPy64-31110\python-3.11.1.amd64\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: 	https://chemrxiv.org/engage/chemrxiv/public-api/v1%5Citems?limit=50&skip=0&searchDateFrom=2017-01-01&searchDateTo=2023-05-08
```

After reading through past issues and PRs, I noticed that https://chemrxiv.org/engage/chemrxiv/public-api/v1 was a valid address, and found that '%5C' is the hex code for '\\'. So I manually stitched together a valid URL in `get_dumps\utils\chemrxiv\chemrxiv_api.query_generator` by replacing

`r = self.request(os.path.join(self.base, query), method, params=params)`
with 
`r = self.request(self.base+"/"+query, method, params=params)`

Result: A bunch of JSONs were dumped in `server_dumps`, each corresponding to a single paper.

**Comment by jannisborn** [comment]
Hi @LioHong,

Thanks for the interest in `paperscraper` and reporting this issue. This is caused by your OS being Windows, I should not have used `os.path.join` to join URLs. 

Sorry for that, I will fix it soon in a PR

**Comment by jannisborn** [comment]
But this is correct. First one `.json` is created for each paper, and later they are aggregated into a single `.jsonl` that contains one entry per line. The `.json` files will then be deleted automatically, but if the code stops during scraping (like in your case), you will find only the `.json` files, not the `jsonl` yet

**Comment by jannisborn** [comment]
@LioHong Please have a look at #29

**Comment by LioHong** [comment]
I manually added the fixed code yesterday and successfully ran `chemrxiv()`. Thanks for your help!

**Comment by jannisborn** [comment]
Thanks. I will push a new version to pypi tomorrow
